spring:
  application:
    name: springbootcrud
  datasource:

    url: jdbc:mysql://localhost:3306/ticketdb
    username: root
    password: Avinash@1110
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9090
  servlet:
    context-path: /springbootcrud

